get_its_estimates <- function() {
    ## From Zhang et al. 2019.
    ##
    ## The effect sizes that were examined in this simulation‐based
    ## calculation are defined as (i) total intervention effect size,
    ## which is the sum of expected level change in two intervention
    ## phases (first‐level intervention and second‐level intervention)
    ## plus the expected trend change in two intervention phases over
    ## its standard deviation, (ii) effect size in total level change,
    ## which is the sum of expected level change in two intervention
    ## phases over its standard deviation, and (iii) effect size in
    ## total trend change, which is the sum of expected trend change
    ## in two intervention phases over its standard deviation. Here,
    ## the standard deviation refers to the standard deviation of the
    ## random error in the ITS segmented time series regression
    ## model. It can be estimated from fitting the model to
    ## preintervention data or relevant data from previous studies in
    ## power and sample size calculation.

    ## Load data, which was generated by running
    ## create_taft_its_data.R on the server
    its.data <- readRDS("taft-its-data.Rds")
    its.data$time <- 1:nrow(its.data)

    ## Estimate standard deviation of the error term 
    fit <- lm(in.hospital.mortality ~ time, data = its.data)
    sd.residuals <- sd(fit$residuals)

    ## Simulate intervention data
    transition.time <- 12
    pre.post.observations <- (nrow(its.data)-transition.time)/2
    its.data$phase <- as.factor(c(rep(1, pre.post.observations), rep(2, transition.time), rep(3, pre.post.observations)))
    its.data$simulated.effect <- its.data$in.hospital.mortality
    its.data$simulated.effect[its.data$phase == 2] <- its.data$simulated.effect[its.data$phase == 2] - 0.025
    its.data$simulated.effect[its.data$phase == 3] <- its.data$simulated.effect[its.data$phase == 3] - 0.05

    ## Create interrupted time series model
    phase.1.fit <- lm(simulated.effect ~ time, data = its.data[its.data$phase == 1, ])
    phase.1.level <- phase.1.fit$coefficients["(Intercept)"]
    phase.1.slope <- phase.1.fit$coefficients["time"]
    phase.2.fit <- lm(simulated.effect ~ time, data = its.data[its.data$phase == 2, ])
    phase.2.level <- phase.2.fit$coefficients["(Intercept)"]
    phase.2.slope <- phase.2.fit$coefficients["time"]
    phase.3.fit <- lm(simulated.effect ~ time, data = its.data[its.data$phase == 3, ])
    phase.3.level <- phase.3.fit$coefficients["(Intercept)"]
    phase.3.slope <- phase.3.fit$coefficients["time"]

    ## Estimate effect size, assuming only a change in level
    total.level.change <- phase.1.level - phase.2.level + phase.2.level - phase.3.level
    effect.size.i <- (phase.2.level + phase.3.level)/sd.residuals

    ## Get autocorrelation estimates, up to a lag of 10
    autocorrelation.estimates <- acf(its.data$in.hospital.mortality, plot = FALSE, lag.max = 10)$acf
}
