toc: true
toc-depth: 3
number-sections: true
fig-caption: true
link-bibliography: false
titlepage-theme:
  title-fontsize: 15
  subtitle-fontstyle: ["bfseries"]
  subtitle-fontsize: 20
format:
  titlepage-pdf:
    keep-tex: true
    titlepage: classic-lined
    documentclass: scrartcl
    number-sections: true 
    include-in-header: 
      text: |
        \usepackage{typearea}
        \usepackage{lscape}
        \usepackage{afterpage}
        \usepackage{changepage}
        \usepackage{scrlayer-scrpage}
        \usepackage{soul}
        \usepackage{lastpage}
        \lohead{ADVANCE TRAUMA Trial Protocol}
        \rohead{ClinicalTrials.gov ID NCT06321419}
        \cfoot{\thepage\ of \pageref{LastPage} }
#  docx: default
#  html:
#    minimal: true