---
title: Data Safety Monitoring Committee (DSMC) Charter
subtitle: "Effects of Advanced Trauma Life Support^®^ Training Compared to Standard Care on Adult Trauma Patient Outcomes: A Cluster Randomised Trial"
---

```{r setup}
#| echo: FALSE

noacsr::source_all_functions()
attach(global_variables())
```

# Synopsis

{{< include synopsis.qmd >}}

# Objective of the DSMC

To monitor trial data for each batch, assessing various aspects to ensure the safety of participants, the integrity of the data, and the ethical conduct of the trial.

# DSMC Composition

## Members

Comprising four external members with expertise in clinical trial management, biostatistics, medical ethics, and the relevant clinical field.

## Selection Process

Members are independently selected, ensuring no conflicts of interest with trial sponsors or management.

## Roles and Responsibilities

The Chairperson coordinates the committee, ensuring effective review of data and adherence to the charter.

# Meetings

## Frequency

Meetings to coincide with the completion of data collection for each batch, so `r number_to_text(batches)` meetings in total during the trial period of `r number_to_text(ceiling(total.months/12))` years.

## Format

Flexible to accommodate in-person or virtual meetings.

## Reporting

Documenting and communicating outcomes and recommendations to the trial management group.

# Data Review Process

## Data Quality and Completeness

Regular review of data for accuracy and completeness.

## Inclusion and Follow-up Rates

Assess cluster performance in inclusion of patients participants and track loss to follow-up rates.

## External Factors

Evaluate external factors potentially impacting trial validity.

## Interim Analysis

Review results of interim analyses. There will be one interim analysis after half of the batches have completed the trial. The first purpose of this interim analysis will be to assess the trial's feasibility and recommend stopping the trial if the trial is not feasible, for example if clusters fail to adhere to the randomisation schedule or if there are substantial missing data in outcomes. The second purpose of the interim analysis will be to assess if sample size calculations should be revised, primarily by increasing the number of clusters to be included.

## Safety Monitoring

Scrutinize safety events reported by the trial management group.

# Decision-Making Criteria

## Stopping Rules

The DSMC should recommend stopping the trial if the trial is not feasible, for example if clusters fail to adhere to the randomisation schedule or if there are substantial missing data in outcomes. The DSMC should also recommend stopping the trial if there is a safety concern based on the reporting of safety events.

## Recommendations

Process for making and communicating recommendations to the trial steering committee.

# Confidentiality

## Data Handling

Ensuring strict confidentiality and integrity in data handling.

## Conflict of Interest

Procedures to identify and manage any conflicts of interest.

# Charter Amendments

Procedure for Modifications: Defined process for any necessary amendments to the charter.

# Appendices

Relevant Documents: Including trial protocol, statistical analysis plan, and interim analysis plan.