toc: true
toc-depth: 4
number-sections: true
number-depth: 4
fig-caption: true
link-bibliography: false
titlepage-logo: logo.png
titlepage-theme:
  title-fontsize: 15
  title-fontfamily: "Roboto"
  subtitle-fontstyle: ["bfseries"]
  subtitle-fontsize: 20
  subtitle-fontfamily: "Quicksand"
  elements: ["\\logoblock", "\\titleblock", "\\authorblock"] 
format:
  titlepage-pdf:
    titlepage: classic-lined
    documentclass: scrartcl
    number-sections: true 
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{scrlayer-scrpage}
        \usepackage{lastpage}
        \lohead{ADVANCE TRAUMA SAP}
        \rohead{ClinicalTrials.gov ID NCT06321419}
        \cfoot{\thepage\ of \pageref{LastPage} }
        \usepackage[T1]{fontenc}
        \usepackage{ebgaramond}
        \usepackage[sfdefault]{roboto}
        \usepackage{etoolbox}
        \renewcommand{\familydefault}{\rmdefault}
        \setkomafont{disposition}{\sffamily}
        \setkomafont{pagehead}{\sffamily}

  # docx: default
  # html: default
  