toc: true
toc-depth: 4
number-sections: true
number-depth: 4
fig-caption: true
link-bibliography: false
titlepage-theme:
  page-color: "secondary"
  title-fontfamily: "Roboto"
  title-fontsize: 36
  title-spacing: 44
  title-fontstyle: ["mdseries"]
  title-color: "white"
  subtitle-fontfamily: "Roboto"
  subtitle-fontsize: 28
  subtitle-spacing: 30
  subtitle-fontstyle: ["sffamily"]
  subtitle-color: "white"
  footer-fontfamily: "Roboto"
  footer-fontstyle: ["LARGE"]
  footer-color: "white"
  footer-space-after: 0pt
  elements: ["\\advancetraumabrand", "\\titleblock", "\\vfill", "\\footerblock", "\\textcolor{white}{\\hrule}", "\\par", "\\vspace*{0.5cm}", "\\bgroup\\LARGE\\sffamily\\titlepageurl\\egroup"]
format:
  titlepage-pdf:
    titlepage: formal
    documentclass: scrartcl
    number-sections: true 
    keep-tex: true
    include-in-header: 
      file: in-header.tex
  docx: default
  # html: default
