
#### Inclusion criteria

**Clusters** must meet the following criteria:

- admit or refer/transfer for admission at least 400 patients with trauma per year or 35 patients with trauma per month for at least the last six months;
- provide surgical and orthopaedic emergency services around the clock; and
- have at most 25% of physicians providing initial trauma care trained in a formalised trauma life support training programme, like ATLS^®^ or Primary Trauma Care (PTC).

Additionally, the units to be trained within the cluster must meet the following criteria:

- admits or refers/transfers for admission at least 12 patients with trauma per month for at least the last six months; and
- no more than 25% of physicians providing initial trauma care trained in a formalised trauma life support training programme.

#### Exclusion criteria

**Hospitals** are excluded if they meet any of the following criteria:

- implement a formalised trauma life support training programme [^note:concurrent-training-programmes] during the trial period; or
- plan to implement or implement other major interventions[^note:major-interventions] that affects trauma care during the trial period.

[^note:concurrent-training-programmes]: These include but are not limited to the National Emergency Life Support (NELS) programme, the Basic Trauma Life Support (BTLS) programme, the Pre-Hospital Trauma Life Support (PHTLS) programme, the Trauma Nursing Core Course (TNCC) and the Advanced Trauma Care for Nurses (ATCN) programme.

[^note:major-interventions]: These include but are not limited to implementing of a trauma team approach, opening a trauma centre and  implementing a trauma quality improvement programme.