## Funding

This trial is not yet fully funded. The Trial Management Group has decided to proceed with the trial with the expectation that additional funding will be secured. The Trial Steering Committee will be informed of the funding status at each meeting. If funding is not secured, the trial will be stopped. This will likely result in an underpowered trial. The justification for this decision is that the intervention is considered standard of care in many countries and the data collection is considered minimal risk. There is therefore a very small risk of harm to patient participants, but a potential direct benefit to those patient participants who receive the intervention. The benefit-risk ratio is therefore considered to be favourable, even in the case of an underpowered trial. 

## Potential amendments

There are ongoing discussions about re-framing the trial as a hybrid effectiveness-implementation trial and include a cost-effectiveness analysis. This would involve adding additional data collection to assess the implementation and costs of the intervention. This would involve additional funding and amended ethical approvals.