# Trial Organization

Trial management and oversight is governed by four trial committees and groups: the Trial Team (TT), the Trial Management Group (TMG), the Trial Steering Committee (TSC) and the Data Monitoring Committee (DMC). These groups are briefly described below and their relationships are shown in Figure X. Details about each committee and group are available in their respective charter.

## Trial team

### Responsibility

To run the trial on a day-to-day basis, maintain trial databases, randomise clusters, ensuring complete and correct data, preparing reports for meetings (including those of the TMG, TSC and DMC) and dealing with research governance and, if appropriate, regulatory matters.

### Composition

Includes the project manager, clinical research associates, principal investigator and co-investigators as needed. 

### Relationships

Reports to the TMG, TSC and DMC. Operationalises decisions made by the TMG.

### Meeting frequencies

As often as needed, often weekly or bi-weekly.

## Trial Management Group (TMG)

### Responsibility

To manage the trial, including its clinical and practical aspects.

### Composition

Includes members with broad expertise appropriate to the trial. The TMG will be chaired by the Principal Investigator.  

### Relationships

Receives reports from TT. Provides input to the TSC and DMC. Implements decisions made by the TSC.

### Meeting frequencies

Monthly to every six months.

## Trial Steering Committee (TSC)

### Responsibility

The TSC's responsibility is to oversee the trial and offer guidance to the TMG.

### Composition

A majority of independent members, including a chair, and a minority of members with a direct interest in the trial, including the principal investigator. The chair should be independent of the trial, the sponsor, and the coordinator.

### Relationships

Receives reports from the trial team and DMC.

### Meeting frequencies

Yearly, but may be more frequent if needed.

## Data Monitoring Committee (DMC)

### Responsibility

To continuously monitoring trial data to ensure participant safety, data integrity, and ethical conduct. 

### Composition

Four external experts specializing in clinical trial management, biostatistics, medical ethics, and the pertinent clinical area.

### Relationships

Reports to the TSC. Receives reports from the TT.

### Meeting frequencies

After the completion of each batch, but may be more frequent if needed.

```{mermaid}
sequenceDiagram
    participant TT as Trial Team
    participant TMG as Trial Management Group
    participant DMC as Data Monitoring Committee
    participant TSC as Trial Steering Committee
    
    TT ->> TMG: Report
    TT ->> DMC: Report
    TT ->> TSC: Report
    TMG ->> TSC: Report
    TSC ->> DMC: Report
    DMC ->> TSC: Recommendations
    TSC ->> TMG: Recommendations
    TMG ->> TT: Recommendations

```

```{mermaid}
flowchart TB
    node TT as "Trial Team"
    TT["Trial Team"] --> TMG["Trial Management Group"]
    TT --> DMC["Data Monitoring Committee"]
    TT --> TSC["Trial Steering Committee"]
    TMG --> TSC
    TMG --> DMC
    DMC --> TSC
```

```{mermaid}
stateDiagram-v2
    %%{init:{'flowchart':{'nodeSpacing': 80, 'rankSpacing': 100}}}%%
    direction TB
    TT: <b>Trial Team</b>
    TT: Runs the trial on a day-to-day basis
    
    TMG: <b>Trial Management Group</b>
    TMG: Implements actions and decisions <br> made by the TSC and DMC

    TSC: <b>Trial Steering Committee</b>
    TSC: Oversees the trial and offers <br> guidance to the TMG

    DMC: <b>Data Monitoring Committee</b>
    DMC: Monitors trial data to ensure <br> participant safety, data integrity, <br> and ethical conduct
    
    TT --> TMG: Report
    TT --> DMC: Report
    TT --> TSC: Report

    TMG --> TSC: Report
    TMG --> TT: Recommend
    
    DMC --> TSC: Report

    TSC --> TMG: Recommend
```