---
subtitle: Trial Management Group meeting, October 11th 2024
title: ADVANCE TRAUMA
reference-doc: ../reference-doc.docx
format: pdf
---

# Members present

-   Martin Gerdin Wärnberg (chair) (MGW)
-   Samriddhi Ranjan (SR)
-   Monty Khajanchi (MK)
-   Li Felländer-Tsai (LFT)
-   Johanna Berg (JB)
-   Kapil Dev Soni (KDS)
-   Shamita Chatterjee (SC)
-   Rajdeep Singh (RS)
-   Prashant Kharat (PK)

# Members excused

-   Nobhojit Roy (NR)
-   Debojit Basak (DB)
-   Karla Hemming (KH)
-   Abhinav Bassi (AB)
-   Lovisa Strömmer (LS)
-   Girish D Bakhshi (GB)
-   Anurag Mishra (AM)
-   Vivekanand Jha (VJ)

# Additional attendees

# Agenda

1. Introduction of new members

2. Update on site progress

3. Presentation of Joint Steering and Data Monitoring Committee

4. Roll out meeting with site PIs and Clinical Research Coordinators on October 19th 

5. Additional points

# Notes and decisions

1. Anna Olofsson, biostatistician from Karolinska Institutet who will be the trial statistician, introduced herself. 

2. We have received ethical approval from four of the five sites in the first batch, and have received a positive response from the fifth site. The sites participating in the first batch are:

    - Government Medical College & Hospital, Chandigarh.
    - Himalayan Institute of Medical Sciences, Dehradun.
    - Christian Medical College and Hospital, Ludhiana.
    - H.B.T. Medical College & Dr. R.N. Cooper Municipal General Hospital, Mumbai.
    - IPGMER & SSKM Hospital, Kolkata.

3. The members of the Joint Trial Steering and Data Monitoring Committee are:

- Ganesan Karthikeyan (Chair, Independent Member). Clinical, interventional cardiologist and a Professor of Cardiology at All India Institute of Medical Sciences, New Delhi, India.
- Richard Hooper (Independent Member, Statistician). Professor of Medical Statistics at Queen Mary University of London, UK.
- Kathryn Chu (Independent Member, Clinical expert). Director and Professor of Global Surgery at Centre for Global Surgery, Stellenbosch
University, South Africa.
- Elamurugan TP (Independent Member, Clinical expert). Additional Professor of Surgery and Associate Dean at Jawaharlal Institute of Postgraduate Medical Education and Research, Puducherry, India.
- Sai Kulkarni (Independent Member, Lay representative).

4. There will be an information and site initation meeting with site investigators and clinical research coordinators on October 19th. The meeting will be held virtually. A link will be sent out to all participants.

5. Additional points:

- We discussed the logistics involved in training residents in ATLS, as well as how to select whom to train. The intention is to maximize the density of trained residents present in the emergency department when the participating units are on call. There have been some misunderstanding regarding this goal of the training, so many sites have attempted to select one or two residents per unit, rather than all residents in the same unit. We will clarify this with the sites. In addition, we know that in most sites residents rotate between different units at fixed intervals, so to accommodate this, we will not train all ten residents (we have budgeted for an average of ten residents per site) at the same time. If possible, we will instead keep a couple of slots per site, so that we can train residents that get shifted into the unit after the initial training.
- We also clarified that we will follow a unit throughout the trial, rather than specific residents. This means that in most sites, the residents will not be the same when the trial ends as when it started. 
- We discussed that the clinical research coordinators need to conduct the ATLS observership before the trial starts. We hope to conduct this observership for as many as possible between October 17 and 18 in Mumbai, but two sited may not have their CRCs ready by then. We will therefore have to find alternative course centres for them, and can only start the trial once they are trained.